### ISSUE TITLE
Inject Command-Arguments with intended Type

### ISSUE THREAD

**Issue by Kronnox** [Cube-Nation/Bedrock#23]
Instead of getting the arguments via the method head as a string.array, specify the specific type and perform automatic type checking via argument constraints.

**Comment by Kronnox** [comment]
Possible data types:
- String (one word)
- Integer
- Double / Float
- BedrockPlayer (online)
- BedrockOfflinePlayer
- (boolean? or "on"/"off" stuff)
- Quoted Multiword String
- Infinite String (Java Varargs) (only last parameter)

Maybe support custom types defined in other plugins, e.g. "Questid" "NPC-ID" and so on.

**Comment by Kronnox** [comment]
### Examples

`/home tp <player> <name>`:
```
public void execute(BedrockChatSender sender, BedrockPlayer player, String homeName) {
```

`/msg <player> <message>`:
```
public void execute(BedrockChatSender sender, BedrockPlayer player, String ... msg) {
```

`/pay <player> <amount>`:
```
public void execute(BedrockChatSender sender, BedrockOfflinePlayer player, int amount) {
```

**Comment by Archerymaister** [comment]
Additional data type:
UUID
